package TimeTableLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum DayName {
  Sunday("Sunday", "Sunday"),
  Monday("Monday", "Monday"),
  Tuesday("Tuesday", "Tuesday"),
  Wednesday("Wednesday", "Wednesday"),
  Thursday("Thursday", "Thursday"),
  Friday("Friday", "Friday"),
  Saturday("Saturday", "Saturday");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<DayName> getConstants() {
    List<DayName> list = ListSequence.fromList(new LinkedList<DayName>());
    ListSequence.fromList(list).addElement(DayName.Sunday);
    ListSequence.fromList(list).addElement(DayName.Monday);
    ListSequence.fromList(list).addElement(DayName.Tuesday);
    ListSequence.fromList(list).addElement(DayName.Wednesday);
    ListSequence.fromList(list).addElement(DayName.Thursday);
    ListSequence.fromList(list).addElement(DayName.Friday);
    ListSequence.fromList(list).addElement(DayName.Saturday);
    return list;
  }

  public static DayName getDefault() {
    return DayName.Sunday;
  }

  public static DayName parseValue(String value) {
    if (value == null) {
      return DayName.getDefault();
    }
    if (value.equals(DayName.Sunday.getValueAsString())) {
      return DayName.Sunday;
    }
    if (value.equals(DayName.Monday.getValueAsString())) {
      return DayName.Monday;
    }
    if (value.equals(DayName.Tuesday.getValueAsString())) {
      return DayName.Tuesday;
    }
    if (value.equals(DayName.Wednesday.getValueAsString())) {
      return DayName.Wednesday;
    }
    if (value.equals(DayName.Thursday.getValueAsString())) {
      return DayName.Thursday;
    }
    if (value.equals(DayName.Friday.getValueAsString())) {
      return DayName.Friday;
    }
    if (value.equals(DayName.Saturday.getValueAsString())) {
      return DayName.Saturday;
    }
    return DayName.getDefault();
  }

  private String myValue;

  DayName(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
