package TimeTableLang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Timetable_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Timetable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TimeTableLang.structure.Timetable";
  }
}
