package TimeTableLang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TimeSpan_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TimeSpan_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TimeTableLang.structure.TimeSpan";
  }
}
