package TimeTableLang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TimeLiteral_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TimeLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TimeTableLang.structure.TimeLiteral";
  }
}
