package TimeTableLang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TimeSpanLiteral_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TimeSpanLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TimeTableLang.structure.TimeSpanLiteral";
  }
}
