package TimeTableLang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class TimeSpanLiteral_Constraints extends BaseConstraintsDescriptor {
  public TimeSpanLiteral_Constraints() {
    super("TimeTableLang.structure.TimeSpanLiteral");
  }
}
