/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.SubGrLangGrammarAccess;

public class SubGrLangParser extends AbstractContentAssistParser {
	
	@Inject
	private SubGrLangGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalSubGrLangParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalSubGrLangParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalSubGrLangParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getFollowRecordAccess().getGroup(), "rule__FollowRecord__Group__0");
					put(grammarAccess.getModelAccess().getPersonsAssignment(), "rule__Model__PersonsAssignment");
					put(grammarAccess.getPersonAccess().getNameAssignment_1(), "rule__Person__NameAssignment_1");
					put(grammarAccess.getPersonAccess().getFollowingAssignment_2(), "rule__Person__FollowingAssignment_2");
					put(grammarAccess.getFollowRecordAccess().getPersonAssignment_1(), "rule__FollowRecord__PersonAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalSubGrLangParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalSubGrLangParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SubGrLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SubGrLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
