package TimeTableLang.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.jetbrains.mps.openapi.model.SNode;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_8117425987505878606(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "Timetable" + SPropertyOperations.getString_def(_context.getNode(), "name", "Sunday");
  }

  public static Object propertyMacro_GetPropertyValue_8117425987505923861(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "name", "Sunday");
  }

  public static Object propertyMacro_GetPropertyValue_8117425987506062662(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8117425987506087340(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "at", true), "from", true), "hours") + ":" + SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "at", true), "from", true), "minutes") + " - " + SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "at", true), "to", true), "hours") + ":" + SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "at", true), "to", true), "minutes");
  }

  public static Object propertyMacro_GetPropertyValue_8117425987506328216(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), "inRoom") + "";
  }

  public static Object propertyMacro_GetPropertyValue_8117425987506389175(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "presenter");
  }

  public static Iterable sourceNodesQuery_8117425987505942467(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "lectures", true)).sort(new ISelector<SNode, Integer>() {
      public Integer select(SNode it) {
        return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(it, "at", true), "from", true), "hours") * 1000 + SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(it, "at", true), "from", true), "minutes");
      }
    }, true);
  }
}
