/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SubGrLangUiModule extends org.xtext.example.mydsl.ui.AbstractSubGrLangUiModule {
	public SubGrLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
