/*
* generated by Xtext
*/
package org.xtext.example.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SubGrLangStandaloneSetup extends SubGrLangStandaloneSetupGenerated{

	public static void doSetup() {
		new SubGrLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

